replicaCount: 2
image:
  repository: <your_ecr_url>
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: flask.vodafone.local
      paths:
        - /
